version: "3.8"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - rickymorty-node-redis-cache:/var/lib/postgresql/data

volumes:
  rickymorty-node-redis-cache: null
